In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('Datos geo Madrid/geo_distritos.csv',sep =',')
df

,geom,cartodb_id,objectid_1,objectid,cusec,cumun,csec,cdis,cmun,cpro,...,nmun,shape_leng,estado,obs,superf_m2,shape_area,shape_len,seccion,nombre,poblacion
0,"POLYGON((-3.32053457555518 40.5501017055762, -...",20140,0,20244,2808301002,28083,2,1,83,28,...,Meco,1379.307923,I,NaN,119046,1.190458e+05,1379.307923,2808301002,Meco,2693
1,"POLYGON((-3.32579244666982 40.5495847967221, -...",20142,0,20246,2808301004,28083,4,1,83,28,...,Meco,12789.340025,I,NaN,6705040,6.705040e+06,12789.340025,2808301004,Meco,2753
2,"POLYGON((-3.3222111892899 40.5559343038948, -3...",20143,0,20247,2808301005,28083,5,1,83,28,...,Meco,3430.325077,I,NaN,411510,4.115096e+05,3430.325077,2808301005,Meco,2485
3,"POLYGON((-3.31608555683787 40.584073152043, -3...",20141,0,20245,2808301003,28083,3,1,83,28,...,Meco,25306.957629,I,NaN,17338786,1.733879e+07,25306.957629,2808301003,Meco,3444
4,"POLYGON((-3.30671018189774 40.5785377081149, -...",20139,0,20243,2808301001,28083,1,1,83,28,...,Meco,16438.581716,I,NaN,10349914,1.034991e+07,16438.581716,2808301001,Meco,2529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4339,"POLYGON((-4.39693833797757 40.3610322533443, -...",20636,0,20743,2813301003,28133,3,1,133,28,...,San Martín de Valdeiglesias,51182.867088,I,NaN,61542668,6.154267e+07,51182.867088,2813301003,San Martín de Valdeiglesias,2442
4340,"POLYGON((-4.34738423209109 40.3628235678141, -...",20637,0,20744,2813301004,28133,4,1,133,28,...,San Martín de Valdeiglesias,16726.964926,I,NaN,7198801,7.198801e+06,16726.964926,2813301004,San Martín de Valdeiglesias,1360
4341,"POLYGON((-4.37913453415264 40.4074726222989, -...",20635,0,20742,2813301002,28133,2,1,133,28,...,San Martín de Valdeiglesias,20561.731915,I,NaN,17710613,1.771061e+07,20561.731915,2813301002,San Martín de Valdeiglesias,2590
4342,"POLYGON((-3.56858480443603 40.9044289507467, -...",20923,0,21032,2890101001,28901,1,1,901,28,...,Lozoyuela-Navas-Sieteiglesias,31515.644197,I,NaN,51433744,5.143374e+07,31515.644197,2890101001,Lozoyuela-Navas-Sieteiglesias,1211
4343,"POLYGON((-3.6658487391691 40.9954336263361, -3...",17380,0,17484,2806301001,28063,1,1,63,28,...,Gargantilla del Lozoya y Pinilla de Buitrago,26219.754476,I,NaN,24305592,2.430559e+07,26219.754476,2806301001,Gargantilla del Lozoya y Pinilla de Buitrago,325